### ISSUE TITLE
Array operations in C

### ISSUE THREAD

**Issue by shreyansh-tyagi** [prakhar290/topicwise-c-programs#1]
Hi , I wanted to know if you're ok with me creating a program for array operations in C. Could you let me know where to store the file in the branch ?

**Comment by prakhar290** [comment]
> Hi , I wanted to know if you're ok with me creating a program for array operations in C. Could you let me know where to store the file in the branch ?

yes sure let's discuss what you wanna do...

**Comment by shreyansh-tyagi** [comment]
> > Hi , I wanted to know if you're ok with me creating a program for array operations in C. Could you let me know where to store the file in the branch ?
> 
> yes sure let's discuss what you wanna do...

actually there is one program that hold some basic array operations, take a look at that program and merge it with your repository...
